### ISSUE TITLE
[Feature Request] Index Page Implementation

### ISSUE THREAD

**Issue by jlinville1** [UTDNebula/survival-guide#46] opened 2022-11-10 00:19 UTC
# Overview
Since we cannot implement a search feature at this time, an index is needed as a quick way to find articles. This page should be a simple list that contains all of the articles in the survival guide in alphabetical order. Since we aren't sure how long the MVP will last without a search feature, the index should be easily scalable to contain a large amount of articles. A link to the index should also be placed in common locations that a user would expect a search bar.

# Proposal
In the index page itself, there should be:

- Page title
- Top bar, footer, and sidebar that are consistent with the rest of the site 
- **Two** columns of links to all articles in the website (desktop)
- Endless scrolling (desktop)
- **One** column of all links to all articles in the websites (mobile)
- No more than 25 rows of links (mobile)
- Links should be listed in alphabetical order and left aligned

As for the rest of the website, the index page should be:

- Linked where a search bar would be in the top bar
- Accessible from every page on the website

## Supplementary Information
Here's an [example](https://witcher.fandom.com/wiki/Special:AllPages?from=%22Starry+Night+Over+the+Pontar%22 ) of an index from Fandom.
Our version definitely doesn't have to be this complex, but this contains the main elements we need.

**Comment by WillieCubed** [comment] 2023-02-21 07:09
Closing as duplicate of #47, which has been implemented.

**Closed by WillieCubed** 2023-02-21 07:09 UTC
Labels: Category: User Experience, Status: Awaiting Triage, Type: Feature Request
