### ISSUE TITLE
[Feature Request] Homepage- UTD Web Links

### ISSUE THREAD

**Issue by AvengingPrime** [UTDNebula/survival-guide#50] opened 2022-11-27 01:54 UTC
# Overview
A featured article section to promote articles and allow users to easily find popular articles.

# Proposal
Implement components relevant to the featured article section.

## Supplementary Information
![image](https://user-images.githubusercontent.com/32879528/204115702-f8fa6792-156d-408e-b562-fe89ea99a2e8.png)

**Comment by WillieCubed** [comment] 2023-02-21 07:13
Closing as duplicate of #49

**Closed by WillieCubed** 2023-02-21 07:13 UTC
Labels: Category: User Experience, Status: Awaiting Triage, Type: Feature Request
